const SUPABASE_URL='https://xgidnneeovsqfysleeua.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_bcLO52pj7tmWEHBPxziSH_ElYtHWM0';
const db=supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);
const CATS={travel:'🧳 Travel',bus:'🚌 Bus',eo:'🎪 EO/MICE',corp:'🏢 Corporate',wedding:'💍 Wedding',community:'👥 Community'};
const STATUSES=['Belum dihubungi','Sudah dihubungi','Follow Up','Respon','Deal'];
let contacts=[],statuses=new Map(),templates=new Map(),currentCat='travel',selected=null,session=null;
const $=id=>document.getElementById(id);
const norm=p=>String(p||'').replace(/\D/g,'').replace(/^0/,'62');
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function localDT(v){return v?new Date(v).toISOString().slice(0,16):''}
function msg(c){const t=templates.get(c?.category);if(t)return t.replaceAll('[NAMA]',c?.name||'').replaceAll('\\n','\n');return 'Assalamu’alaikum Bapak/Ibu '+(c?.name||'')+' 🙏\n\nPerkenalkan, kami dari SATU RESTOE Pangandaran.\n\nKami membuka kerja sama untuk kebutuhan rombongan di Pangandaran. 🍽️🌴\n\nBoleh kami kirimkan menu & paket Satu Restoe?\n\nTerima kasih 🙏\nSATU RESTOE PANGANDARAN\nWA 0812-2011-1178'}
async function load(){
  const {data,error}=await db.from('marketing_contacts').select('id,name,city,phone,category,grade,active,notes,updated_at').eq('active',true).order('id');
  if(error){$('appMsg').textContent='Gagal mengambil kontak: '+error.message;return}
  contacts=data||[];
  const {data:t,error:te}=await db.from('marketing_templates').select('category,template').eq('active',true);
  if(!te) templates=new Map((t||[]).map(x=>[x.category,x.template]));
  if(session){const {data:s,error:e}=await db.from('marketing_contact_status').select('*');if(!e)(s||[]).forEach(x=>statuses.set(x.contact_id,x))}
  renderCats();render();newCustomer();
}
function renderCats(){$('cats').innerHTML=Object.entries(CATS).map(([k,v])=>'<button class="'+(k===currentCat?'active':'')+'" onclick="setCat(\''+k+'\')">'+v+'</button>').join('')}
function setCat(k){currentCat=k;selected=null;renderCats();render();newCustomer()}
function visible(){const q=$('search').value.toLowerCase(),sf=$('statusFilter').value,gf=$('gradeFilter').value;return contacts.filter(c=>c.category===currentCat&&(!q||[c.name,c.city,c.phone].join(' ').toLowerCase().includes(q))&&(!sf||((statuses.get(c.id)?.status)||'Belum dihubungi')===sf)&&(!gf||c.grade===gf))}
function renderFollowList(){const el=$('followList');if(!el)return;const now=new Date(),start=new Date(now);start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+1);const arr=contacts.filter(c=>c.category===currentCat).map(c=>({c,s:statuses.get(c.id)||{}})).filter(x=>x.s.next_follow&&x.s.status!=='Deal').sort((a,b)=>new Date(a.s.next_follow)-new Date(b.s.next_follow)).slice(0,20);if(!arr.length){el.textContent='Belum ada follow-up untuk kategori ini.';return}el.innerHTML=arr.map(x=>{const d=new Date(x.s.next_follow),late=d<start,today=d>=start&&d<end;return '<div class="followItem"><div><b>'+esc(x.c.name)+'</b><span>'+esc(x.c.city||'')+' • '+esc(x.c.phone)+'</span><small>'+d.toLocaleString('id-ID')+' — '+(late?'TERLAMBAT':today?'HARI INI':esc(x.s.status||'Follow Up'))+'</small></div><button class="green" onclick="pick('+x.c.id+');openWA()">WA</button></div>'}).join('')}
function renderRecentActivity(){const el=$('recentActivity');if(!el)return;const items=[];contacts.filter(c=>c.category===currentCat).forEach(c=>{const s=statuses.get(c.id)||{};if(Array.isArray(s.history))s.history.forEach(h=>items.push({c,h}))});items.sort((a,b)=>new Date(b.h.date)-new Date(a.h.date));const arr=items.slice(0,15);if(!arr.length){el.textContent='Belum ada aktivitas.';return}el.innerHTML=arr.map(x=>'<div class="followItem"><div><b>'+esc(x.c.name)+'</b><span>'+esc(x.c.city||'')+' • '+esc(x.c.phone)+'</span><small>'+new Date(x.h.date).toLocaleString('id-ID')+' — '+esc(x.h.action)+(x.h.note?' — '+esc(x.h.note):'')+'</small></div><button class="gray" onclick="pick('+x.c.id+')">Buka</button></div>').join('')}
function updateDashboard(){const cat=contacts.filter(c=>c.category===currentCat),today=new Date();today.setHours(0,0,0,0);const tomorrow=new Date(today);tomorrow.setDate(tomorrow.getDate()+1);let follow=0,overdue=0,contacted=0,deals=0;cat.forEach(c=>{const s=statuses.get(c.id)||{},st=s.status||'Belum dihubungi';if(['Sudah dihubungi','Follow Up','Respon','Deal'].includes(st))contacted++;if(st==='Deal')deals++;if(s.next_follow){const d=new Date(s.next_follow);if(d>=today&&d<tomorrow)follow++;else if(d<today&&st!=='Deal')overdue++}});$('todayFollow').textContent=follow;$('overdueFollow').textContent=overdue;$('contacted').textContent=contacted;$('deals').textContent=deals;renderFollowList();renderRecentActivity()}
function filterFollow(kind){$('statusFilter').value='Follow Up';$('search').value='';const now=new Date(),start=new Date(now);start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+1);contacts.filter(c=>c.category===currentCat).forEach(c=>{const s=statuses.get(c.id)||{};if(s.next_follow){const d=new Date(s.next_follow);const ok=kind==='today'?d>=start&&d<end:d<start;if(ok&&s.status!=='Deal'){selected=c;pick(c.id);return}}});render()}
function resetView(){$('search').value='';$('statusFilter').value='';$('gradeFilter').value='';render()}
function render(){const arr=visible();$('tbody').innerHTML=arr.map((c,i)=>{const st=statuses.get(c.id)?.status||'Belum dihubungi';return '<tr onclick="pick('+c.id+')"><td>'+(i+1)+'</td><td>'+esc(c.grade)+'</td><td>'+esc(c.name)+'</td><td>'+esc(c.city)+'</td><td>'+esc(c.phone)+'</td><td>'+esc(st)+'</td></tr>'}).join('');const cat=contacts.filter(c=>c.category===currentCat),count=s=>cat.filter(c=>(statuses.get(c.id)?.status||'Belum dihubungi')===s).length;$('total').textContent=cat.length;$('new').textContent=count('Belum dihubungi');$('follow').textContent=count('Follow Up');$('resp').textContent=count('Respon')+count('Deal');updateDashboard()}
function pick(id){selected=contacts.find(c=>c.id===id)||null;if(!selected)return;const s=statuses.get(id)||{};$('title').textContent=selected.name;$('detail').innerHTML='<b>'+esc(selected.city||'')+'</b> • '+esc(selected.category)+' • '+esc(selected.grade)+'<br>WhatsApp: '+esc(selected.phone);$('status').value=s.status||'Belum dihubungi';$('marketing').value=s.marketing||'';$('lastContact').value=localDT(s.last_contact);$('nextFollow').value=localDT(s.next_follow);$('notes').value=s.notes||'';historyView(s.history||[])}
function quickStatus(st){if(!selected){$('appMsg').textContent='Pilih customer dulu.';return}$('status').value=st;$('appMsg').textContent='Status dipilih: '+st+' — tekan Simpan Status untuk menyimpan.'}
function newCustomer(){$('title').textContent='Pilih Customer';$('detail').textContent='Pilih customer dari daftar.';$('status').value='Belum dihubungi';$('marketing').value='';$('lastContact').value='';$('nextFollow').value='';$('notes').value='';$('history').textContent='Belum ada riwayat.'}
function historyView(h){$('history').innerHTML=h.length?h.slice().reverse().map(a=>'<div class="hist">'+new Date(a.date).toLocaleString('id-ID')+' — <b>'+esc(a.action)+'</b>'+(a.note?' — '+esc(a.note):'')+'</div>').join(''):'Belum ada riwayat.'}
async function saveStatus(){if(!session){$('appMsg').textContent='Silakan login dulu untuk menyimpan status.';return}if(!selected){$('appMsg').textContent='Pilih customer dulu.';return}const old=statuses.get(selected.id)||{};const st=$('status').value;const history=Array.isArray(old.history)?old.history.slice():[];if(old.status!==st||!old.contact_id)history.push({date:new Date().toISOString(),action:st,note:$('notes').value.trim()});const row={contact_id:selected.id,status:st,marketing:$('marketing').value.trim(),last_contact:$('lastContact').value?new Date($('lastContact').value).toISOString():null,next_follow:$('nextFollow').value?new Date($('nextFollow').value).toISOString():null,notes:$('notes').value.trim(),history,updated_by:session.user.id,updated_at:new Date().toISOString()};const {data,error}=await db.from('marketing_contact_status').upsert(row,{onConflict:'contact_id'}).select().single();if(error){$('appMsg').textContent='Gagal menyimpan: '+error.message;return}statuses.set(selected.id,data);render();pick(selected.id);$('appMsg').textContent='Status tersimpan di Supabase.'}
function openWA(){if(!selected)return;const p=norm(selected.phone);window.open('https://wa.me/'+p+'?text='+encodeURIComponent(msg(selected)),'_blank')}
function csvCell(v){return '"'+String(v??'').replaceAll('"','""')+'"'}
function downloadText(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function exportCSV(){const rows=[['Nama','Kategori','Kota','WhatsApp','Prioritas','Status','Marketing','Terakhir Dihubungi','Follow Up','Catatan','History JSON']];contacts.filter(c=>c.category===currentCat).forEach(c=>{const s=statuses.get(c.id)||{};rows.push([c.name,c.category,c.city,c.phone,c.grade,s.status||'Belum dihubungi',s.marketing||'',s.last_contact||'',s.next_follow||'',s.notes||'',JSON.stringify(s.history||[])])});const csv='\\uFEFF'+rows.map(r=>r.map(csvCell).join(',')).join('\n');downloadText('SatuRestoe_'+currentCat+'_web.csv',csv,'text/csv;charset=utf-8')}
function backupJSON(){const payload={format:'SatuRestoe Marketing Backup',version:2,exported_at:new Date().toISOString(),contacts:contacts.map(c=>({contact:c,status:statuses.get(c.id)||null}))};downloadText('SatuRestoe_Marketing_Backup.json',JSON.stringify(payload,null,2),'application/json;charset=utf-8');$('appMsg').textContent='Backup JSON seluruh customer dan history sudah dibuat.'}
function parseCSV(text){
  const rows=[];let row=[],cell='',quoted=false;
  for(let i=0;i<text.length;i++){const ch=text[i],next=text[i+1];if(ch==='"'){if(quoted&&next==='"'){cell+='"';i++}else quoted=!quoted}else if(ch===','&&!quoted){row.push(cell);cell=''}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&next==='\n')i++;row.push(cell);cell='';if(row.some(v=>v.trim()!==''))rows.push(row);row=[]}else cell+=ch}
  if(cell!==''||row.length){row.push(cell);if(row.some(v=>v.trim()!==''))rows.push(row)}
  if(!rows.length)return [];
  const headers=rows[0].map(h=>String(h).replace(/^\uFEFF/,'').trim().toLowerCase());
  return rows.slice(1).map(vals=>Object.fromEntries(headers.map((h,i)=>[h,String(vals[i]??'').trim()])));
}
function getField(r,names){for(const n of names){const k=Object.keys(r).find(x=>x===n||x.replace(/[^a-z0-9]/g,'')===n.replace(/[^a-z0-9]/g,''));if(k&&r[k]!=='')return r[k]}return ''}
function importedRow(r){
  const phone=getField(r,['whatsapp','phone','no hp','no. hp','nomor hp','telepon','no telepon']);
  const status=getField(r,['status'])||'Belum dihubungi';
  if(!phone||!STATUSES.includes(status))return null;
  let history=[];const hs=getField(r,['history json','history','riwayat kontak']);if(hs){try{const x=JSON.parse(hs);if(Array.isArray(x))history=x}catch{}}
  return {phone,status,marketing:getField(r,['marketing']),last_contact:getField(r,['terakhir dihubungi','lastcontact','last contact']),next_follow:getField(r,['follow up','jadwal follow up','nextfollow','next follow']),notes:getField(r,['catatan','notes']),history};
}
async function importBackupFile(file){
  if(!session){$('appMsg').textContent='Login dulu untuk import backup.';return}
  const text=await file.text();let rows=[];
  if(file.name.toLowerCase().endsWith('.json')){let payload;try{payload=JSON.parse(text)}catch{$('appMsg').textContent='File JSON tidak valid.';return}rows=(payload.contacts||[]).filter(x=>x.status&&x.status.status).map(x=>{const c=x.contact||{},s=x.status;return {phone:c.phone||x.phone,status:s.status,marketing:s.marketing||'',last_contact:s.last_contact||'',next_follow:s.next_follow||'',notes:s.notes||'',history:Array.isArray(s.history)?s.history:[]}})}
  else rows=parseCSV(text).map(importedRow).filter(Boolean);
  if(!rows.length){$('appMsg').textContent='Tidak ada baris backup yang bisa diimport.';return}
  const byPhone=new Map(contacts.map(c=>[norm(c.phone),c]));let matched=0,skipped=0,changed=0;
  for(const r of rows){const c=byPhone.get(norm(r.phone));if(!c){skipped++;continue}matched++;const old=statuses.get(c.id)||{};let history=r.history.length?r.history.slice():(Array.isArray(old.history)?old.history.slice():[]);if(!r.history.length)history.push({date:new Date().toISOString(),action:'Import backup',note:'Status/data diimpor dari file backup'});const row={contact_id:c.id,status:r.status,marketing:r.marketing||'',last_contact:r.last_contact?new Date(r.last_contact).toISOString():null,next_follow:r.next_follow?new Date(r.next_follow).toISOString():null,notes:r.notes||'',history,updated_by:session.user.id,updated_at:new Date().toISOString()};const {data,error}=await db.from('marketing_contact_status').upsert(row,{onConflict:'contact_id'}).select().single();if(error){$('appMsg').textContent='Import berhenti: '+error.message;return}statuses.set(c.id,data);changed++}
  render();if(selected)pick(selected.id);$('appMsg').textContent='Import selesai: '+changed+' customer diperbarui, '+skipped+' nomor tidak ditemukan di database.';
}
async function login(){const email=$('email').value.trim();if(!email)return;$('loginMsg').textContent='Mengirim link...';const {error}=await db.auth.signInWithOtp({email,options:{emailRedirectTo:location.origin+location.pathname}});$('loginMsg').textContent=error?error.message:'Link login sudah dikirim ke email.'}
async function logout(){await db.auth.signOut()}
$('todayBtn').onclick=()=>filterFollow('today');$('overdueBtn').onclick=()=>filterFollow('overdue');$('resetViewBtn').onclick=resetView;
$('search').oninput=render;$('statusFilter').onchange=render;$('gradeFilter').onchange=render;$('saveBtn').onclick=saveStatus;$('waBtn').onclick=openWA;$('exportBtn').onclick=exportCSV;$('backupBtn').onclick=backupJSON;$('importFile').onchange=e=>{const f=e.target.files?.[0];if(f)importBackupFile(f);e.target.value=''};$('sendOtp').onclick=login;$('loginBtn').onclick=()=>$('loginCard').classList.toggle('hidden');$('logoutBtn').onclick=logout;
db.auth.onAuthStateChange(async(_event,s)=>{session=s;$('loginBtn').classList.toggle('hidden',!!s);$('logoutBtn').classList.toggle('hidden',!s);$('loginCard').classList.toggle('hidden',!!s);statuses=new Map();await load()});
load();